SELECT 
     p.globalid,
     'state' as "admin_level",
     null as "settlement_name",
     TRIM(p.statecode) as "state_code",
     TRIM(p.statename) as "state_name",
     null as "lga_code",
     null as "lga_name",
     null as "ward_code",
     null as "ward_name",
     p.one_four, p.five_nine,
     p.ten_fourteen, p.fifteen_nineteen,
     p.twenty_twentyfour, p.twentyfive_twentynine,
     p.thirty_thirtyfour, p.thirtyfive_thirtynine,
     p.forty_fortyfour, p.fortyfive_fortynine,
     p.fifty_fiftyfour, p.fiftyfive_fiftynine,
     p.sixty_sixtyfour, p.sixtyfive_sixtynine,
     p.seventy_seventyfour, p.seventyfive_hundred,
     p.total_pop
FROM vts_pop.southsouth_pop_state as p
UNION SELECT 
     p.globalid,
     'lga' as "admin_level",
     null as "settlement_name",
     TRIM(p.statecode) as "state_code",
     null as "state_name",
     TRIM(p.lgacode) as "lga_code",
     TRIM(p.lganame) as "lga_name",
     null as "ward_code",
     null as "ward_name",
     p.one_four, p.five_nine,
     p.ten_fourteen, p.fifteen_nineteen,
     p.twenty_twentyfour, p.twentyfive_twentynine,
     p.thirty_thirtyfour, p.thirtyfive_thirtynine,
     p.forty_fortyfour, p.fortyfive_fortynine,
     p.fifty_fiftyfour, p.fiftyfive_fiftynine,
     p.sixty_sixtyfour, p.sixtyfive_sixtynine,
     p.seventy_seventyfour, p.seventyfive_hundred,
     p.total_pop
FROM vts_pop.southsouth_pop_lga as p
UNION SELECT
     p.globalid,
     'ward' as "admin_level",
     null as "settlement_name",
     null as "state_code",
     null as "state_name",
     TRIM(p.lgacode) as "lga_code",
     null as "lga_name",
     TRIM(p.wardcode) as "ward_code",
     TRIM(p.wardname) as "ward_name",
     p.one_four, p.five_nine,
     p.ten_fourteen, p.fifteen_nineteen,
     p.twenty_twentyfour, p.twentyfive_twentynine,
     p.thirty_thirtyfour, p.thirtyfive_thirtynine,
     p.forty_fortyfour, p.fortyfive_fortynine,
     p.fifty_fiftyfour, p.fiftyfive_fiftynine,
     p.sixty_sixtyfour, p.sixtyfive_sixtynine,
     p.seventy_seventyfour, p.seventyfive_hundred,
     p.total_pop
FROM vts_pop.southsouth_pop_wards as p
UNION SELECT 
     p.globalid,
     'settlement' as "admin_level",
     TRIM(p.settlementname) as "settlement_name",
     null as "state_code",
     null as "state_name",
     null as "lga_code",
     null as "lga_name",
     TRIM(p.wardcode) as "ward_code",
     null as "ward_name",
     p.one_four, p.five_nine,
     p.ten_fourteen, p.fifteen_nineteen,
     p.twenty_twentyfour, p.twentyfive_twentynine,
     p.thirty_thirtyfour, p.thirtyfive_thirtynine,
     p.forty_fortyfour, p.fortyfive_fortynine,
     p.fifty_fiftyfour, p.fiftyfive_fiftynine,
     p.sixty_sixtyfour, p.sixtyfive_sixtynine,
     p.seventy_seventyfour, p.seventyfive_hundred,
     p.total_pop
FROM vts_pop.southsouth_pop_settlement as p
